export const Heroes = [
  // {
  //   id: 1,
  //   card: "card-1",
  //   cardGrid: {
  //     name: "Micheal Egorov",
  //     strength: 16,
  //     defense: 29,
  //     rarity: "common",
  //     hash: 100,
  //     eth: 0.05,
  //     payed: true,
  //     isHero: true,
  //   },
  // },
  // {
  //   id: 2,
  //   card: "card-2",
  //   cardGrid: {
  //     name: "Micheal Egorov",
  //     strength: 16,
  //     defense: 29,
  //     rarity: "common",
  //     hash: 100,
  //     eth: 0.047,
  //     payed: true,
  //     isHero: true,
  //   },
  // },
  // {
  //   id: 3,
  //   card: "card-3",
  //   cardGrid: {
  //     name: "Micheal Egorov",
  //     strength: 16,
  //     defense: 29,
  //     rarity: "common",
  //     hash: 100,
  //     eth: 0.05,
  //     payed: true,
  //     isHero: true,
  //   },
  // },
  // {
  //   id: 4,
  //   card: "card-4",
  //   cardGrid: {
  //     name: "Micheal Egorov 4",
  //     strength: 16,
  //     defense: 29,
  //     rarity: "common",
  //     hash: 100,
  //     eth: 0.047,
  //     payed: true,
  //     isHero: true,
  //   },
  // },
  // {
  //   id: 5,
  //   card: "card-5",
  //   cardGrid: {
  //     name: "Micheal Egorov - 5",
  //     strength: 16,
  //     defense: 29,
  //     rarity: "common",
  //     hash: 100,
  //     eth: 0.047,
  //     payed: true,
  //     isHero: true,
  //   },
  // },
  // {
  //   id: 6,
  //   card: "card-6",
  //   cardGrid: {
  //     name: "Micheal Egorov 6",
  //     strength: 16,
  //     defense: 29,
  //     rarity: "common",
  //     hash: 100,
  //     eth: 0.047,
  //     payed: true,
  //     isHero: true,
  //   },
  // },
];
