const actions = {
  GET_FINISH_TEAM_ID_PER_USER_STATUS: "GET_FINISH_TEAM_ID_PER_USER_STATUS",
  GET_FINISH_TEAM_ID_PER_USER_STATUS_SUCCESS: "GET_FINISH_TEAM_ID_PER_USER_STATUS_SUCCESS",
  GET_FINISH_TOTAL_HASH_PER_TEAM_STATUS: "GET_FINISH_TOTAL_HASH_PER_TEAM_STATUS",
  GET_FINISH_TOTAL_HASH_PER_TEAM_STATUS_SUCCESS: "GET_FINISH_TOTAL_HASH_PER_TEAM_STATUS_SUCCESS",

  getFinishTeamIdPerUserStatus: () => ({
    type: actions.GET_FINISH_TEAM_ID_PER_USER_STATUS,
    payload: {}
  }),
  getFinishTotalHashPerTeamStatus: () => ({
    type: actions.GET_FINISH_TOTAL_HASH_PER_TEAM_STATUS,
    payload: {}
  }),
};

export default actions;
