const actions = {
  GET_BATTLE_START_DATE_STATUS: "GET_BATTLE_START_DATE_STATUS",
  GET_BATTLE_START_DATE_STATUS_SUCCESS: "GET_BATTLE_START_DATE_STATUS_SUCCESS",
  GET_TEAM_ID_PER_USER_STATUS: "GET_TEAM_ID_PER_USER_STATUS",
  GET_TEAM_ID_PER_USER_STATUS_SUCCESS: "GET_TEAM_ID_PER_USER_STATUS_SUCCESS",
  GET_TOTAL_HASH_PER_TEAM_STATUS: "GET_TOTAL_HASH_PER_TEAM_STATUS",
  GET_TOTAL_HASH_PER_TEAM_STATUS_SUCCESS: "GET_TOTAL_HASH_PER_TEAM_STATUS_SUCCESS",
  GET_DAY_HASH_PER_TEAM_STATUS: "GET_DAY_HASH_PER_TEAM_STATUS",
  GET_DAY_HASH_PER_TEAM_STATUS_SUCCESS: "GET_DAY_HASH_PER_TEAM_STATUS_SUCCESS",
  GET_TOTAL_HASH_PER_USER_STATUS: "GET_TOTAL_HASH_PER_USER_STATUS",
  GET_TOTAL_HASH_PER_USER_STATUS_SUCCESS: "GET_TOTAL_HASH_PER_USER_STATUS_SUCCESS",
  GET_DAY_HASH_PER_USER_STATUS: "GET_DAY_HASH_PER_USER_STATUS",
  GET_DAY_HASH_PER_USER_STATUS_SUCCESS: "GET_DAY_HASH_PER_USER_STATUS_SUCCESS",
  SELECT_TEAM_STATUS: "SELECT_TEAM_STATUS",
  SELECT_TEAM_STATUS_SUCCESS: "SELECT_TEAM_STATUS_SUCCESS",

  getBattleStartDateStatus: (time) => ({
    type: actions.GET_BATTLE_START_DATE_STATUS,
    payload: { time }
  }),
  getTeamIdPerUserStatus: () => ({
    type: actions.GET_TEAM_ID_PER_USER_STATUS,
    payload: {}
  }),
  getTotalHashPerTeamStatus: () => ({
    type: actions.GET_TOTAL_HASH_PER_TEAM_STATUS,
    payload: {}
  }),
  getDayHashPerTeamStatus: (teamId) => ({
    type: actions.GET_DAY_HASH_PER_TEAM_STATUS,
    payload: { teamId }
  }),
  getTotalHashPerUserStatus: () => ({
    type: actions.GET_TOTAL_HASH_PER_USER_STATUS,
    payload: {}
  }),
  getDayHashPerUserStatus: () => ({
    type: actions.GET_DAY_HASH_PER_USER_STATUS,
    payload: {}
  }),
  selectTeam: (teamId, callback) => ({
    type: actions.SELECT_TEAM_STATUS,
    payload: { teamId, callback }
  }),
};

export default actions;
